/** ==================================================================
 * cros2_polygonstamped_support.hpp
 * Class for interfacing a native Connext DDS application with the 
 *  ROS 2 geometry_msgs::msg::dds_::PolygonStamped_ data type.
 * This program uses the C++11 option of RTIDDSGen, using the type
 *  support source code generated by the command line:
 *   rtiddsgen -language C++11 <arch> cros2_types.idl
 **/

#ifndef __CROS2_POLYGONSTAMPED_SUPPORT_HPP__
#define __CROS2_POLYGONSTAMPED_SUPPORT_HPP__
#include "cros2_common.hpp"             // common includes and defs
#include "geometry_msgs/msg/PolygonStampedPlugin.hpp"

/** ----------------------------------------------------------------
 * cros2polygonstamped class
 * This class supports ROS2 PolygonStamped_
 * ------------------------------------------------------------- **/
class cros2polygonstamped
{
public:
    cros2polygonstamped(const std::string polygonstampedName, uint32_t opt_en, dds::domain::DomainParticipant participant,
        int(*rcv_fptr)(dds::sub::DataReader<geometry_msgs::msg::dds_::PolygonStamped_>) = NULL);
    ~cros2polygonstamped();

    void publish(void);
    geometry_msgs::msg::dds_::PolygonStamped_ *sample_to_pub(void) { return &pub_sample; }

    // polygonstamped data sample accessors
    void pub_sample_header_tstamp_set(int32_t newSec, uint32_t newNanosec) { 
        pub_sample.header().stamp().sec(newSec); 
        pub_sample.header().stamp().nanosec(newNanosec);
    }
    void pub_sample_header_frameid_set(const std::string newId) { pub_sample.header().frame_id(newId); }
    void pub_sample_size_set(int32_t newSize) { pub_sample.polygon().points().resize(newSize); }
    void pub_sample_point_set(int32_t idx, float x, float y, float z) {
        pub_sample.polygon().points().at(idx).x(x);
        pub_sample.polygon().points().at(idx).y(y);
        pub_sample.polygon().points().at(idx).z(z);
    }

    int data_rcv_count_get(void) { return data_rcv_count; }

private:
    // DDS receive data handler
    int rcv_dataProc(dds::sub::DataReader<geometry_msgs::msg::dds_::PolygonStamped_> & reader);

    // DDS Topic, DataWriter, DataReader, Sample(for publish)
    dds::topic::Topic<geometry_msgs::msg::dds_::PolygonStamped_> data_topic;
    dds::pub::DataWriter<geometry_msgs::msg::dds_::PolygonStamped_> data_wr;
    dds::sub::DataReader<geometry_msgs::msg::dds_::PolygonStamped_> data_rd;
    geometry_msgs::msg::dds_::PolygonStamped_ pub_sample;

    // misc
    dds::core::cond::WaitSet waitset;
    int data_rcv_count;
};
#endif  // ndef __CROS2_POLYGONSTAMPED_SUPPORT_HPP__